 version: 0.2

 env:
   variables:
     AWS_DEFAULT_REGION: "ap-northeast-2"
     ECR_URL: "171679447334.dkr.ecr.ap-northeast-2.amazonaws.com"
     ECR_REPO: "order-api-registry"
     ECR_IMAGE_TAG: "1.0.0"

 phases:
  pre_build:
    commands:
      - echo Logging to Amazon ECR
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_URL}
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - docker build -t order-api:${ECR_IMAGE_TAG} .
      - echo Build Done
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${ECR_URL}/${ECR_REPO}:${ECR_IMAGE_TAG}

 artifacts:
   files:
     - deploy/appspec.yml
     - deploy/scripts/kill_process.sh
     - deploy/scripts/run_process.sh
     - deploy/docker-compose.yml
   discard-paths: yes

 cache:
   paths:
     - '/root/.gradle/caches/**/*'