server:
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: default

  lifecycle:
    timeout-per-shutdown-phase: 2000

  datasource:
    url: jdbc:mysql://localhost:3306/order?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: localhost
    port: 6379

---
spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'

  lifecycle:
    timeout-per-shutdown-phase: 2000

  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: orderapi