server:
  shutdown: graceful
  port: 8080

spring:
  config:
    activate:
      on-profile: default
    import: 'aws-parameterstore:'

  lifecycle:
    timeout-per-shutdown-phase: 2000

  datasource:
    url: jdbc:mysql://localhost:3308/order?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 30
      read-only: false
      connection-timeout: 3000
      connectionTestQuery : SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: orderapi

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${access.key}
      secret-key: ${secret.key}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug

---
server:
  tomcat:
    threads:
      max: 300
    accept-count: 150

spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'

  lifecycle:
    timeout-per-shutdown-phase: 2000

  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    hikari:
      maximum-pool-size: 30
      read-only: false
      connection-timeout: 3000
      connectionTestQuery: SELECT 1

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: ${redis.host}
    port: 6379

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: orderapi

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: ${access.key}
      secret-key: ${secret.key}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug