server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 2000

  config:
    activate:
      on-profile: prod

  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.pwd}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
