server:
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: default

  lifecycle:
    timeout-per-shutdown-phase: 2000

  datasource:
    url: jdbc:mysql://localhost:3308/order?characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 30
      read-only: false
      connection-timeout: 1000
      connectionTestQuery : SELECT 1


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        format_sql: true

  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug

---
spring:
  config:
    activate:
      on-profile: prod
    import: 'aws-parameterstore:'

  lifecycle:
    timeout-per-shutdown-phase: 2000

  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    hikari:
      maximum-pool-size: 30
      read-only: false
      connection-timeout: 1000
      connectionTestQuery: SELECT 1

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    host: ${redis.host}
    port: 6379

aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: orderapi

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

logging:
  level:
    com.zaxxer.hikari.pool.HikariPool: debug