### 아이템 등록
POST http://localhost:8080/api/v1/items
Content-Type: application/json

{
  "partnerToken": "ptn_cphggBHTWtFXYVjq",
  "itemName": "후드-C",
  "itemPrice": 48000,
  "itemOptionGroupList": [
    {
      "ordering": "1",
      "itemOptionGroupName": "사이즈",
      "itemOptionList": [
        {
          "ordering": 1,
          "itemOptionName": "SMALL",
          "itemOptionPrice": 0
        },
        {
          "ordering": 2,
          "itemOptionName": "MEDIUM",
          "itemOptionPrice": 0
        },
        {
          "ordering": 3,
          "itemOptionName": "LARGE",
          "itemOptionPrice": 0
        }
      ]

    },
    {
      "ordering": "2",
      "itemOptionGroupName": "컬러",
      "itemOptionList": [
        {
          "ordering": 1,
          "itemOptionName": "BLACK",
          "itemOptionPrice": 0
        },
        {
          "ordering": 2,
          "itemOptionName": "WHITE",
          "itemOptionPrice": 0
        }
      ]
    }
  ]
}

### 아이템 조회
GET http://localhost:8080/api/v1/items/itm_jqVQTXgHWhIIoCki