### 주문 요청 초기 저장
POST http://localhost:8082/api/v1/orders
Content-Type: application/json

{
  "payMethod": "NAVER_PAY",
  "receiverName": "홍당무",
  "receiverPhone": "01012341234",
  "receiverZipcode": "12345",
  "receiverAddress1": "서울시 강동구",
  "receiverAddress2": "우리집",
  "etcMessage": "감사합니다",
  "orderItemList": [
    {
      "orderCount": 1,
      "itemToken": "itm_zVUmlTrEzdDtjeWB",
      "itemName": "후드 A",
      "itemPrice": "48000",
      "orderItemOptionGroupList": [
        {
          "ordering": 1,
          "itemOptionGroupName": "사이즈",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "MEDIUM",
              "itemOptionPrice": 0
            }
          ]
        },
        {
          "ordering": 2,
          "itemOptionGroupName": "컬러",
          "orderItemOptionList": [
            {
              "ordering": 1,
              "itemOptionName": "BLACK",
              "itemOptionPrice": 0
            }
          ]
        }
      ]
    }
  ]
}

### 주문 결제 처리
POST http://localhost:8080/api/v1/orders/payment-order
Content-Type: application/json

{
  "orderToken": "ord_lqAcdTqvORlU7ry3",
  "payMethod": "NAVER_PAY",
  "amount": "72000",
  "orderDescription": "주문테스트"
}

### 주문 조회
GET http://localhost:8080/api/v1/orders/ord_lqAcdTqvORlU7ry3
